version: '3.8'

services:
  frontend:
    # build: ./frontend
    image: ghcr.io/florian-projects/queueuify/queueify-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./certificates:/etc/nginx/ssl
    depends_on:
      - backend

  backend:
    # build: ./backend
    image: ghcr.io/florian-projects/queueuify/queueify-backend:latest
    ports:
      - "8000:8000"
    environment:
      spotify_client_id: ${spotify_client_id}
      spotify_client_secret: ${spotify_client_secret}
      redirect_uri: ${redirect_uri}
      root_path: ${root_path}

      db_user: ${DB_USER}
      db_password: ${DB_PASSWORD}
      db_host: "db"
      db_port: 3306
      db_name: ${DB_NAME}
    depends_on:
      - db
    volumes:
      - ./certificates:/certificates
    expose:
      - 8000
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
