version: "3"
services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: docker
      MARIADB_DATABASE: docker
      MARIADB_USER: docker
      MARIADB_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: